routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/forum', [

	'uses' => 'ForumsController@index',
	'as' => 'forum'

]);

Route::get('{provider}/auth', [

	'uses' => 'SocialsController@auth',
	'as' => 'social.auth' 

]);

Route::get('/{provider}/redirect', [

	'uses' => 'SocialsController@auth_callback',
	'as' => 'social.callback'

]);

Route::get('/discussion/{slug}', [

	'uses' => 'DiscussionsController@show',
	'as' => 'discussion'

]);

Route::get('/channel/{slug}', [

	'uses' => 'ForumsController@channel',
	'as' => 'channel'
]);

Route::group(['middleware' => 'auth'], function() {
    
    Route::resource('channels', 'ChannelsController');

    Route::get('/discussion/create/new', [

    	'uses' => 'DiscussionsController@create',
    	'as' => 'discussions.create'

    ]);

    Route::post('/discussion/store', [

    	'uses' => 'DiscussionsController@store',
    	'as' => 'discussions.store'

    ]);

    Route::post('/discussion/reply/{id}', [

    	'uses' => 'DiscussionsController@reply',
    	'as' => 'discussion.reply'

    ]);

    Route::get('/reply/like/{id}', [

    	'uses' => 'RepliesController@like',
    	'as' => 'reply.like'
    ]);

    Route::get('/reply/unlike/{id}', [

    	'uses' => 'RepliesController@unlike',
    	'as' => 'reply.unlike'
    ]);

    Route::get('/discussion/watch/{id}', [

    	'uses' =>'WatchersController@watch' ,
    	'as' => 'discussion.watch'

    ]);

    Route::get('/discussion/unwatch/{id}', [

    	'uses' =>'WatchersController@unwatch' ,
    	'as' => 'discussion.unwatch'

    ]);

    Route::get('/discussion/best/reply/{id}', [

    	'uses' =>'RepliesController@best_answer' ,
    	'as' => 'discussion.best.answer'

    ]);

    Route::get('/discussions/edit/{slug}', [

    	'uses' =>'DiscussionsController@edit' ,
    	'as' => 'discussion.edit'

    ]);

    Route::post('/discussions/update/{id}', [

    	'uses' =>'DiscussionsController@update' ,
    	'as' => 'discussions.update'

    ]);

    Route::get('/reply/edit/{id}', [

    	'uses' =>'RepliesController@edit' ,
    	'as' => 'reply.edit'

    ]);

    Route::post('/reply/update/{id}', [

    	'uses' =>'RepliesController@update' ,
    	'as' => 'reply.update'

    ]);
    
});

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
    
    protected $fillable = ['title', 'slug'];

    public function discussions()
    {
    	return $this->hasMany('App\Discussion');
    }
}

app/Http/Controllers/ChannelsController.php
<?php

namespace App\Http\Controllers;

use Session;

use App\Channel;

use Illuminate\Http\Request;

class ChannelsController extends Controller
{

    public function __construct()
    {
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('channels.index')->with('channels', Channel::all());

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('channels.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request, [

            'channel' => 'required'

        ]);

        Channel::create([

            'title' => $request->channel,
            'slug' => str_slug($request->channel)

        ]);

        Session::flash('success', 'Channel Created');

        return redirect()->route('channels.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $channel = Channel::find($id);

        return view('channels.edit')->with('channel', $channel);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [

            'channel' => 'required'

        ]);

        $channel = Channel::find($id);

        $channel->title = $request->channel;
        $channel->slug = str_slug($request->channel);
        $channel->save();

        Session::flash('success', 'Channel updated');

        return redirect()->route('channels.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        Channel::destroy($id);

        Session::flash('success', 'Channel deleted');

        return redirect()->route('channels.index');
    }
}

resources/views/channels/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Create a new channel</div>

        <div class="card-body">
            
            <form action="{{ route('channels.store') }}" method="POST">
                {{ csrf_field() }}
                
                <div class="form-group">
                    <input type="text" name="channel" class="form-control" required="">
                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">
                            Save Channel
                        </button>
                    </div>
                </div>

            </form>

        </div>
    </div>
        
@endsection

resources/views/channels/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Edit channel: {{ $channel->title }}</div>

        <div class="card-body">
            
            <form action="{{ route('channels.update', ['channel' => $channel->id]) }}" method="post">

                {{ csrf_field() }}

                {{ method_field('PUT') }}
                
                <div class="form-group">
                    <input type="text" name="channel" class="form-control" value="{{ $channel->title }}" required="">
                </div>
                <div class="form-group">
                    <div class="text-center">
                        <button class="btn btn-success" type="submit">
                            Update Channel
                        </button>
                    </div>
                </div>

            </form>

        </div>
    </div>
       
@endsection

resources/views/channels/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Channels</div>

        <div class="card-body">
            
            <table class="table table-hover">
                <thead>
                    <th>
                        Name
                    </th>
                    <th>
                        Edit
                    </th>
                    <th>
                        Delete
                    </th>
                </thead>                    

                <tbody>
                    @foreach($channels as $channel)

                        <tr>
                            <td>{{ $channel->title }}</td>
                            <td>
                                <a href="{{ route('channels.edit', ['channel' => $channel->id]) }}" class="btn btn-xs btn-info">Edit</a>
                            </td>
                            <td>
                                <form action="{{ route('channels.destroy', ['channel' => $channel->id]) }}" method="post">

                                    {{ csrf_field() }}

                                    {{ method_field('DELETE') }}

                                    <button class="btn btn-xs btn-danger" type="submit">Delete</button>

                                </form>
                            </td>
                        </tr>

                    @endforeach
                </tbody>

            </table>

        </div>
    </div>
            
@endsection